remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme@latest
plugins:
- jekyll-remote-theme

nav_item:
    - { url: '/', text: 'Home' }
    - { url: '/philosophy', text: 'Philosophy' }
    - { url: '/goals', text: 'Goals' }

# {% include contact.html %}
# {% include contact-modal.html %}
